name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: first step
        run: echo "tes"
